/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in and start a session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the signed-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rolls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Roll a dice expression */
        post: operations["rollDice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether the API and its database are up */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /**
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @enum {string} */
        Role: "SOLO_PLAYER" | "GAME_MANAGER" | "OWNER";
        CurrentUserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @description Independent roles: none implies another (ADR 0006). */
            roles: components["schemas"]["Role"][];
        };
        ErrorResponse: {
            /** @description A human-readable message; never says whether an email exists. */
            error: string;
        };
        RollRequest: {
            /**
             * @description Dice notation: NdM, "d%", keep/drop selectors (kh, kl, dh, dl, k), integers, + - * / and parentheses. Case-insensitive; whitespace ignored.
             * @example 4d6kh3+2
             */
            expression: string;
        };
        RolledDieResponse: {
            /**
             * @description The face the die landed on.
             * @example 5
             */
            value: number;
            /** @description Whether the die counts towards the total; false when a selector dropped it. */
            kept: boolean;
        };
        DiceGroupResponse: {
            /** @example 4d6kh3 */
            notation: string;
            /** @example 6 */
            sides: number;
            /** @description Every die rolled, in roll order, dropped ones included. */
            dice: components["schemas"]["RolledDieResponse"][];
            /**
             * @description The sum of the kept dice.
             * @example 14
             */
            subtotal: number;
        };
        RollResponse: {
            /**
             * @description The normalized notation: lower case, no whitespace, "d" as "1d", "d%" as "d100", "k" as "kh".
             * @example 4d6kh3+2
             */
            expression: string;
            /**
             * @description The value of the expression, counting kept dice only.
             * @example 16
             */
            total: number;
            /** @description Every dice group, in notation order; empty when the expression rolls no dice. */
            groups: components["schemas"]["DiceGroupResponse"][];
        };
        HealthResponse: {
            /**
             * @description The application answered the request.
             * @enum {string}
             */
            status: "ok";
            /**
             * @description Whether the database answers right now.
             * @enum {string}
             */
            database: "ok" | "down";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; the response sets the HttpOnly session cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description The JSON body is malformed or misses a field. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many failed attempts; try again later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out (also when there was no session). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rollDice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollRequest"];
            };
        };
        responses: {
            /** @description The roll: its total and every die rolled, dropped ones included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollResponse"];
                };
            };
            /** @description The JSON body is malformed or has no string "expression". */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The expression is not valid dice notation, exceeds a limit or divides by zero. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is up; the database status is reported separately. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
