/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in and start a session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the signed-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my campaigns */
        get: operations["listCampaigns"];
        put?: never;
        /** Create a campaign pinned to the latest release of a GameSystem */
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one of my campaigns */
        get: operations["getCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the next session of one of my campaigns */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaignId}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the next scene in the current session of one of my campaigns */
        post: operations["startScene"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/play/game-systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the GameSystems a campaign can be created with */
        get: operations["listGameSystems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/likelihood-answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a likelihood oracle a yes/no question */
        post: operations["askLikelihoodOracle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oracle-table-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Roll on an oracle table, following nested tables */
        post: operations["resolveOracleTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rolls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Roll a dice expression */
        post: operations["rollDice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether the API and its database are up */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /**
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /** Format: password */
            password: string;
        };
        /** @enum {string} */
        Role: "SOLO_PLAYER" | "GAME_MANAGER" | "OWNER";
        CurrentUserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @description Independent roles: none implies another (ADR 0006). */
            roles: components["schemas"]["Role"][];
        };
        ErrorResponse: {
            /** @description A human-readable message; never says whether an email exists. */
            error: string;
        };
        CampaignSummaryResponse: {
            /** Format: uuid */
            id: string;
            /** @example The lost mine */
            name: string;
            /** @example ironsworn */
            gameSystemKey: string;
            /** @example Ironsworn */
            gameSystemName: string;
            /**
             * @description The release version the campaign is pinned to.
             * @example 3
             */
            releaseVersion: number;
            /** Format: date-time */
            createdAt: string;
        };
        CreateCampaignRequest: {
            /**
             * @description Trimmed; not blank.
             * @example The lost mine
             */
            name: string;
            /**
             * @description A GameSystem from `GET /api/play/game-systems`; the campaign is pinned to its latest release.
             * @example ironsworn
             */
            gameSystemKey: string;
        };
        PinnedReleaseResponse: {
            /** @example ironsworn */
            gameSystemKey: string;
            /** @example Ironsworn */
            gameSystemName: string;
            /** @example 3 */
            version: number;
        };
        SceneResponse: {
            /**
             * @description Numbered from 1 within its session.
             * @example 1
             */
            number: number;
            /** @example At the gate */
            title: string;
            /** Format: date-time */
            startedAt: string;
        };
        SessionResponse: {
            /**
             * @description Numbered from 1 within the campaign.
             * @example 1
             */
            number: number;
            /** Format: date-time */
            startedAt: string;
            /** @description In number order; empty right after the session starts. */
            scenes: components["schemas"]["SceneResponse"][];
        };
        OracleTableResponse: {
            /** @example weather */
            key: string;
            /** @example Weather */
            name: string;
        };
        LikelihoodLevelResponse: {
            /**
             * @description The likelihood to ask the oracle with.
             * @example likely
             */
            key: string;
            /** @example Likely */
            label: string;
        };
        LikelihoodChaosResponse: {
            /** @example 1 */
            min: number;
            /** @example 9 */
            max: number;
            /** @example 5 */
            neutral: number;
        };
        LikelihoodOracleResponse: {
            /** @example fate */
            key: string;
            /** @example Fate question */
            name: string;
            /** @description In definition order. */
            levels: components["schemas"]["LikelihoodLevelResponse"][];
            /** @description Null when the oracle takes no chaos factor. */
            chaos: components["schemas"]["LikelihoodChaosResponse"] | null;
        };
        CampaignResponse: {
            /** Format: uuid */
            id: string;
            /** @example The lost mine */
            name: string;
            /** Format: date-time */
            createdAt: string;
            pinnedRelease: components["schemas"]["PinnedReleaseResponse"];
            /** @description In number order. */
            sessions: components["schemas"]["SessionResponse"][];
            /**
             * @description The latest session; null before the first one.
             * @example 2
             */
            currentSessionNumber: number | null;
            /**
             * @description The latest scene of the current session; null when it has none yet.
             * @example 1
             */
            currentSceneNumber: number | null;
            /** @description The oracle tables of the pinned release, in definition order. */
            oracleTables: components["schemas"]["OracleTableResponse"][];
            /** @description The likelihood oracles of the pinned release, in definition order. */
            likelihoodOracles: components["schemas"]["LikelihoodOracleResponse"][];
        };
        StartSceneRequest: {
            /**
             * @description Trimmed; not blank.
             * @example At the gate
             */
            title: string;
        };
        GameSystemSummaryResponse: {
            /**
             * @description The key to create a campaign with.
             * @example ironsworn
             */
            gameSystemKey: string;
            /** @example Ironsworn */
            name: string;
            /** @description Null when the release has no description. */
            description: string | null;
            /**
             * @description The version a new campaign is pinned to.
             * @example 3
             */
            version: number;
        };
        LikelihoodLevelDefinition: {
            /**
             * @description a-z, 0-9 and "-".
             * @example likely
             */
            key: string;
            /** @example Likely */
            label: string;
            /**
             * @description The highest roll that answers yes at the neutral chaos factor; 0 to sides.
             * @example 65
             */
            target: number;
        };
        /** @description The effective target is the level's target + (chaosFactor − neutral) × shiftPerPoint, clamped to 0…sides; min ≤ neutral ≤ max. */
        LikelihoodChaosDefinition: {
            /** @example 1 */
            min: number;
            /** @example 9 */
            max: number;
            /**
             * @description The chaos factor used when none is given.
             * @example 5
             */
            neutral: number;
            /**
             * @description Target points added per chaos point above neutral; 0 to sides.
             * @example 5
             */
            shiftPerPoint: number;
        };
        /** @description Rolls 1d<sides> = R against the effective target T: yes when R ≤ T. With p = exceptionalPercent, the yes is exceptional when R ≤ floor(T × p / 100), the no when R > sides − floor((sides − T) × p / 100). */
        LikelihoodOracleDefinition: {
            /** @example 100 */
            sides: number;
            /** @description The likelihoods a question can be asked with; unique keys. */
            levels: components["schemas"]["LikelihoodLevelDefinition"][];
            /** @description Absent when the oracle has no chaos factor. */
            chaos?: components["schemas"]["LikelihoodChaosDefinition"] | null;
            /**
             * @description Size of the exceptional bands, in percent; 0 by default.
             * @example 20
             */
            exceptionalPercent?: number | null;
        };
        LikelihoodAnswerRequest: {
            oracle: components["schemas"]["LikelihoodOracleDefinition"];
            /**
             * @description The key of the likelihood level to ask with.
             * @example likely
             */
            likelihood: string;
            /**
             * @description Within the oracle's chaos range; the neutral one when absent. Only allowed when the oracle has chaos.
             * @example 5
             */
            chaosFactor?: number | null;
        };
        LikelihoodAnswerResponse: {
            /**
             * @description Yes when the roll is at most the effective target, no otherwise; exceptional within the oracle's exceptional bands.
             * @example yes
             * @enum {string}
             */
            answer: "exceptional_yes" | "yes" | "no" | "exceptional_no";
            /**
             * @description The roll on 1d<sides>.
             * @example 42
             */
            roll: number;
            /** @example 100 */
            sides: number;
            /**
             * @description The level's target shifted by the chaos factor and clamped to 0…sides.
             * @example 65
             */
            effectiveTarget: number;
            /**
             * @description The key of the likelihood level asked with.
             * @example likely
             */
            likelihood: string;
            /** @example Likely */
            likelihoodLabel: string;
            /**
             * @description The chaos factor used (the neutral one when none was given); null when the oracle has no chaos.
             * @example 5
             */
            chaosFactor: number | null;
        };
        /** @description Ranged entries have "min" and "max"; weighted entries may have a "weight" (1 by default). An entry needs a "text" unless it nests a "table". */
        OracleTableEntryDefinition: {
            /**
             * @description Lowest total this entry covers, on a ranged table.
             * @example 1
             */
            min?: number | null;
            /**
             * @description Highest total this entry covers, on a ranged table.
             * @example 3
             */
            max?: number | null;
            /**
             * @description Relative chance of this entry, on a weighted table; 1 by default.
             * @example 2
             */
            weight?: number | null;
            /** @example Clear */
            text?: string | null;
            /**
             * @description The key of a table of the set to roll on next when this entry is selected.
             * @example storm-kind
             */
            table?: string | null;
        };
        /** @description A ranged table has "dice" and entries with "min" and "max" that do not overlap; a weighted table has no "dice", entries with an optional "weight" and rolls 1dW for total weight W. */
        OracleTableDefinition: {
            /**
             * @description Unique within the table set: a-z, 0-9 and "-".
             * @example weather
             */
            key: string;
            /** @example Weather */
            name: string;
            entries: components["schemas"]["OracleTableEntryDefinition"][];
            /**
             * @description Dice notation rolled on a ranged table; absent on a weighted table.
             * @example 1d6
             */
            dice?: string | null;
        };
        OracleTableResultRequest: {
            /** @description The table set: unique keys; nested tables must be in the set, never cycle and nest at most 10 levels deep. */
            tables: components["schemas"]["OracleTableDefinition"][];
            /**
             * @description The key of the table to roll on.
             * @example weather
             */
            table: string;
        };
        OracleTableStepResponse: {
            /** @example weather */
            tableKey: string;
            /** @example Weather */
            tableName: string;
            /**
             * @description The normalized notation rolled: the table's dice, or "1dW" for a weighted table of total weight W.
             * @example 1d6
             */
            dice: string;
            /**
             * @description The total rolled, which selected the entry.
             * @example 6
             */
            total: number;
            /**
             * @description The selected entry's text; may be empty when the entry nests a table.
             * @example Storm
             */
            text: string;
            /**
             * @description The table the next step rolls on; null on the last step.
             * @example storm-kind
             */
            nestedTableKey: string | null;
        };
        OracleTableResultResponse: {
            /**
             * @description The key of the table rolled on first.
             * @example weather
             */
            table: string;
            /** @description One step per table rolled, root first; a step with a nestedTableKey is followed by the roll on that table. */
            steps: components["schemas"]["OracleTableStepResponse"][];
        };
        RollRequest: {
            /**
             * @description Dice notation: NdM, "d%", keep/drop selectors (kh, kl, dh, dl, k), integers, + - * / and parentheses. Case-insensitive; whitespace ignored.
             * @example 4d6kh3+2
             */
            expression: string;
        };
        RolledDieResponse: {
            /**
             * @description The face the die landed on.
             * @example 5
             */
            value: number;
            /** @description Whether the die counts towards the total; false when a selector dropped it. */
            kept: boolean;
        };
        DiceGroupResponse: {
            /** @example 4d6kh3 */
            notation: string;
            /** @example 6 */
            sides: number;
            /** @description Every die rolled, in roll order, dropped ones included. */
            dice: components["schemas"]["RolledDieResponse"][];
            /**
             * @description The sum of the kept dice.
             * @example 14
             */
            subtotal: number;
        };
        RollResponse: {
            /**
             * @description The normalized notation: lower case, no whitespace, "d" as "1d", "d%" as "d100", "k" as "kh".
             * @example 4d6kh3+2
             */
            expression: string;
            /**
             * @description The value of the expression, counting kept dice only.
             * @example 16
             */
            total: number;
            /** @description Every dice group, in notation order; empty when the expression rolls no dice. */
            groups: components["schemas"]["DiceGroupResponse"][];
        };
        HealthResponse: {
            /**
             * @description The application answered the request.
             * @enum {string}
             */
            status: "ok";
            /**
             * @description Whether the database answers right now.
             * @enum {string}
             */
            database: "ok" | "down";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; the response sets the HttpOnly session cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description The JSON body is malformed or misses a field. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many failed attempts; try again later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out (also when there was no session). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listCampaigns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in player's campaigns, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSummaryResponse"][];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The user is not a solo player. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignRequest"];
            };
        };
        responses: {
            /** @description The new campaign; the Location header is its URL. */
            201: {
                headers: {
                    /** @description The URL of the new campaign. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description The JSON body is malformed or has no string "name" or "gameSystemKey". */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The user is not a solo player. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The GameSystem has no published release. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The generated campaign id is already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The name is blank or too long. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The campaign. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The user is not a solo player. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No campaign of the player has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The campaign, the new session current and without a scene. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The user is not a solo player. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No campaign of the player has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The campaign already holds the most sessions it can. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startScene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSceneRequest"];
            };
        };
        responses: {
            /** @description The campaign, the new scene current. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description The JSON body is malformed or has no string "title". */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The user is not a solo player. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No campaign of the player has this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The campaign has no session yet, or the current session holds the most scenes it can. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The title is blank or too long. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listGameSystems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest published release of each GameSystem, by name ignoring case, then key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSystemSummaryResponse"][];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The user is not a solo player. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    askLikelihoodOracle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LikelihoodAnswerRequest"];
            };
        };
        responses: {
            /** @description The answer, the roll and the effective target it was compared with. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikelihoodAnswerResponse"];
                };
            };
            /** @description The JSON body is malformed, has no "oracle" object (a non-empty JSON list is not one) or no string "likelihood", or a non-integer "chaosFactor". */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The oracle is invalid, it has no such likelihood level, or the chaos factor is out of range or given without chaos. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resolveOracleTable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OracleTableResultRequest"];
            };
        };
        responses: {
            /** @description Every table rolled on, root first, with the dice, total and selected entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OracleTableResultResponse"];
                };
            };
            /** @description The JSON body is malformed, or has no "tables" list (a JSON object is not one) or no string "table". */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The tables are invalid, none has the key asked, or a roll matches no entry. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rollDice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollRequest"];
            };
        };
        responses: {
            /** @description The roll: its total and every die rolled, dropped ones included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollResponse"];
                };
            };
            /** @description The JSON body is malformed or has no string "expression". */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The body is not JSON. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The expression is not valid dice notation, exceeds a limit or divides by zero. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is up; the database status is reported separately. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
