<?php

declare(strict_types=1);

namespace App\Play\Domain\Campaign;

/**
 * A campaign with this id was already created. Ids are generated by the caller, so a repeated
 * command (or a colliding id) must not replace the existing campaign.
 */
final class CampaignAlreadyExists extends \DomainException
{
    public static function withId(CampaignId $id): self
    {
        return new self(\sprintf('A campaign with id "%s" already exists.', $id->toString()));
    }
}
