<?php

declare(strict_types=1);

namespace App\Play\Domain\Journal;

/**
 * A journal entry with this id was already recorded. Ids are generated by the caller, so a
 * repeated command (or a colliding id) must not record a second entry.
 */
final class JournalEntryAlreadyExists extends \DomainException
{
    public static function withId(JournalEntryId $id): self
    {
        return new self(\sprintf('A journal entry with id "%s" already exists.', $id->toString()));
    }
}
